# Spins a local database to store sample products data
version: '3.8'
services:
  postgres:
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      - PGUSER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=stock-tracker

